# This contains the protein and atoms selections for the CTD (chains A & D)

sel_CTD_A     = 'protein and bynum 9054:11750'
sel_CTD_D     = 'protein and bynum 44304:47000'
sel_AD_CTD    = f'{sel_CTD_A} or {sel_CTD_D}'

sel_fp11_A    = '(protein and resid 688 686 684 690 694 761 726 759 753 and bynum 9054:11750)'
sel_fp11_D    = '(protein and resid 658 660 659 661 680 and bynum 44304:47000)'
sel_fp11_AD   = f'{sel_fp11_A} or {sel_fp11_D}'
sel_fp11_AD_heavy = f'{sel_fp11_AD} and not name H* and not backbone'

